steps:
# Build Ordo frontend
- name: 'gcr.io/cloud-builders/docker'
  id: Build the Ordo image
  args: [
    "build",
    "-t",
    "gcr.io/$PROJECT_ID/site-ordo",
    ".",
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: Push new Ordo image
  args: [
    "push",
    "gcr.io/$PROJECT_ID/site-ordo",
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy Ordo to Cloud Run
  args: [
    "run",
    "deploy",
    "site-ordo",
    "--image",
    "gcr.io/$PROJECT_ID/site-ordo",
    "--region",
    "us-central1",
  ]

images:
  - "gcr.io/$PROJECT_ID/site-ordo"